name: SoundSphere
description: "A simple sound player with multi "
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.5.0 # Mise à jour pour correspondre à cloud_firestore
  firebase_auth: ^5.3.1 # Authentification Firebase (version compatible)
  cloud_firestore: ^5.4.3 # Firestore Firebase
  firebase_storage: ^12.3.1 # Dernière version compatible avec firebase_core
  google_sign_in: ^6.2.1 # Authentification Google
  image_picker: ^0.8.6+3 # Pour sélectionner des images dans le téléphone (version stable)

  # Dependencies for network
  http: ^0.13.4 # Pour les requêtes HTTP
  url_launcher: ^6.0.20 # Pour lancer des URLs externes
  audioplayers: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Le package "flutter_lints" contient un ensemble de règles de lint recommandées
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # Vérifiez la dernière version

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/soundsphere.png" # Chemin vers votre icône
  adaptive_icon_background: "#FFFFFF" # Couleur de fond pour les icônes adaptatives Android
  adaptive_icon_foreground: "assets/icons/soundsphere.png" # Chemin vers l'icône de premier plan

flutter:
  uses-material-design: true
